server:
  port: 8083  # Puerto del servicio de vistas

spring:
  application:
    name: view-service  # Nombre del microservicio
  thymeleaf:
    cache: false  # Desactiva cache en desarrollo para ver cambios en las vistas
  datasource:
    url: jdbc:mysql://localhost:3306/view_db
    username: root
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Crea y actualiza tablas automáticamente
    show-sql: true  # Muestra consultas SQL en la consola
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Registro en Eureka
  instance:
    prefer-ip-address: true

security:
  jwt:
    secret: mySuperSecretKey  # Clave compartida con AuthService

logging:
  level:
    root: INFO
    com.example.view: DEBUG  # Logs detallados en este servicio
